### PR TITLE
Adding workflow-greetings

### PR DESCRIPTION
**Pull request by Sibam-Paul**
closes - #17 

Added greetings workflow 

@Swarnendu0123 Please review my pr and consider it under wob'24

### CODE REVIEW

**Comment by swrno** [comment]
Improve the messages.

**Comment by Sibam-Paul** [comment]
ok what should i write

**Comment by swrno** [comment]
a little descriptive

**Comment by Sibam-Paul** [comment]
Ok

**Comment by Sibam-Paul** [comment]
Ok give me one day will finish it off

**Comment by swrno** [comment]
Is it done?

**Comment by Sibam-Paul** [comment]
Sorry totally forgot my midterm is running will complete  it by tomorrow

**Comment by Sibam-Paul** [comment]
Can u please tell my how descriptive msg I myst write

**Comment by Sibam-Paul** [comment]
Can u plz mark in in the file changed

**Comment by swrno** [comment]
Just change the text, use some text from chatgpt. Which is suitable for issue and pr.

**Comment by Sibam-Paul** [comment]
ok

**Comment by Sibam-Paul** [comment]
@Swarnendu0123 Done

**Comment by Sibam-Paul** [comment]
Please review my pr and consider it under gssoc-ext because
image

**Pull request closed without merging**
