### PR TITLE
Adopted the contract changes with the frontend

### PR DESCRIPTION
**Pull request by ShivRaiGithub**
The contract was modified as discussed along with a public owner instead of private.
Integrated the changes in contract with the frontend.
Also modified the deploy script to make the contract have some data to show.

Attached a screenshot of the working frontend.
Screenshot 2024-09-27 151655

### CODE REVIEW

**Comment by swrno** [comment]
Remove package-lock.jaon

**Comment by ShivRaiGithub** [comment]
It is usually recommended to keep package-lock.json due to various reasons, the most important being prevention of issues that might arise from version differences of package.

**Comment by swrno** [comment]
We don't want to lock the versions.

**Comment by ShivRaiGithub** [comment]
Done

**Comment by swrno** [comment]
Can you please attach a before screenshot, so that I can compare the changes.

**Comment by ShivRaiGithub** [comment]
image

Removed the file.

**Comment by swrno** [comment]
No the repository, I mean the changes in the UI.

**Comment by ShivRaiGithub** [comment]
Screenshot 2024-09-26 091633

The only difference in UI is addition of "Category".

**Comment by swrno** [comment]
Well, I don't think, we should merge this much amount of changes to modify only the category.

**Comment by ShivRaiGithub** [comment]
Its not only the category. Category and breed are both there, however since breed was also previously there in the data, it seems like there isnt any change at first glance. Instead of only numerical id which doesnt provide much info on the pet in contract, the changes made uses the category and breed to define the pet.

**Comment by swrno** [comment]
Well, I don't think the changes are needed. Though thanks for your PR. But I can't accept it.

**Comment by ShivRaiGithub** [comment]
If you think the changes made in contract are unnecessary you could have said earlier when the contract part was provided. Please be careful next time. Time is precious.

**Comment by swrno** [comment]
> If you think the changes made in contract are unnecessary you could have said earlier when the contract part was provided. 

Did you discuss properly what part you want to change?

First of all, you should respect the decision of an Admin or Maintainer. It's not about any program. I have been in open source for the past 2 years. But I have seen the trend of recent open source contributors, that you create a PR by changing something and after 2-3 changes you get frustrated, and then blame the Maintainer. There are discussions which go 1-2 years long in open source. 

First you made some changes in the contract without changing the necessary changes in the frontend. Don't you think if I accept the PR the project frontend will start throwing some error. And when I asked to do the necessary changes in the frontend, again you have tried to convince me to accept the PR without changes.

This clearly shows you have created the PR because you just wanted to get some point, trust me this will not work in the long run. If you are creating any PR, that means you are proposing to change something, maintainers may or may not  accept it. 

> Please be careful next time. Time is precious.

Don't teach the value of time to a maintainer or a project admin. It was your choice to create the PR, no one has forced you to create this PR.

**Pull request closed without merging**
